package com.kunlun.bank.model;

import com.alibaba.fastjson.JSONObject;
import com.jfinal.plugin.activerecord.Page;
import com.kunlun.bank.model.base.BaseOrderInfo;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderInfo extends BaseOrderInfo<OrderInfo> {
	public static final OrderInfo dao = new OrderInfo();
}
