package com.kunlun.bank.model;

import com.kunlun.bank.model.base.BaseTUser;




/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TUser extends BaseTUser<TUser> {
	public static final TUser dao = new TUser();
}
