package cn.five.common.model;

import com.alibaba.fastjson.JSONObject;
import com.jfinal.plugin.activerecord.Page;

import cn.five.common.model.base.BaseCommonInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonInfo extends BaseCommonInfo<CommonInfo> {
	public static final CommonInfo dao = new CommonInfo();
}
