package cn.five.common.model;

import cn.five.common.model.base.BaseTUser;



/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TUser extends BaseTUser<TUser> {
	public static final TUser dao = new TUser();
}
