package cn.five.common.model.base;


import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommonInfo<M extends BaseCommonInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}
	
	public void setSerialNum(java.lang.String serialNum) {
		set("serial_num", serialNum);
	}

	public java.lang.String getSerialNum() {
		return get("serial_num");
	}
	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	public java.lang.String getArea() {
		return get("area");
	}

	public void setTeam(java.lang.String team) {
		set("team", team);
	}

	public java.lang.String getTeam() {
		return get("team");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}

	public java.lang.String getBank() {
		return get("bank");
	}

	public void setProductLine(java.lang.String productLine) {
		set("product_line", productLine);
	}

	public java.lang.String getProductLine() {
		return get("product_line");
	}

	public void setCommonProductId(java.lang.String commonProductId) {
		set("common_product_id", commonProductId);
	}

	public java.lang.String getCommonProductId() {
		return get("common_product_id");
	}

	public void setCommonProduct(java.lang.String commonProduct) {
		set("common_product", commonProduct);
	}

	public java.lang.String getCommonProduct() {
		return get("common_product");
	}

	public void setCommonSalesVolume(java.lang.String commonSalesVolume) {
		set("common_sales_volume", commonSalesVolume);
	}

	public java.lang.String getCommonSalesVolume() {
		return get("common_sales_volume");
	}

	public void setCommonCount(java.lang.String commonCount) {
		set("common_count", commonCount);
	}

	public java.lang.String getCommonCount() {
		return get("common_count");
	}

	public void setProductAttr(java.lang.String productAttr) {
		set("product_attr", productAttr);
	}

	public java.lang.String getProductAttr() {
		return get("product_attr");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setUserHead(java.lang.String userHead) {
		set("user_head", userHead);
	}

	public java.lang.String getUserHead() {
		return get("user_head");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	public java.lang.Integer getStatus(){
		return get("status");
	}
	public void setStatus(java.lang.Integer status){
		set("status",status);
	}
}
